[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
bolt_dragon_crashers = "7SEoX1p2qzA3RwJfWDy5Qbr5eUaX7WHiiQS8gQrhwGgJ"
combat_action = "ETKsaGsmpG5Sm7MnnYEgTTosZCcnZmDmqUvtNg4gEMeC"
combat_init = "6YjSmdFeVvH4upAPTfQtVRhLv9QMtkKf6HP53hxF3RQp"
combat_tick = "HyEV1NvAifHHcUjUvWEEiHwHDNEv72zzoc5JSdz3LTQv"
health = "HcSHqsdjd27qnALpigeyAYTP63Ek666ifg4yYDVxSGbs"
movement = "H3NPkyXoHAvNDX8LXoqbRQ6vW6K3orJn1Hszr2XEmqMy"
name = "7mzf8mMVJ8j2scTrhtkvpvazJB9usdfgUj1jLjNKDaQU"
position = "9CgPjx11JvDGFW2E4NLVRq2bP9PKVaX6uwpznEToucqE"
readyness = "2R2rw36VaaBYtu9xdKq7Voxg8J2L9ZhJV5Fi1yHJqBSH"
speed = "3ZvC3WF9r5kj3nW2rSbYBwkkxTn47R7EnAbWH29xJBr5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/*", "programs-ecs/components/*", "programs-ecs/systems/*"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "WorLD15A7CrDwLcLy4fRqtaTb9fbd8o8iqiEMUDse2n"
program = "tests/fixtures/world.so"
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://rpc.magicblock.app/devnet/"
ledger = ".bolt/test-ledger"
rpc_port = 8899

[[test.validator.account]]
address = "EHLkWwAT9oebVv9ht3mtqrvHhRVMKrt54tF3MfHTey2K"
filename = "tests/fixtures/registry.json"
